name: Deploy to Remote Server

on:
  push:
    branches:
      - master  # You can change this to any branch you want to trigger the deployment

jobs:
  deploy:
    name: Deploy to Remote Server
    runs-on: ubuntu-latest
    timeout-minutes: 120 

    env:
      REPOSITORY_URL: https://github.com/vanshPadia/geini-ai.git
      REMOTE_USER: aipoc
      REMOTE_HOST: 172.30.20.35
      REMOTE_DIR: /home/aipoc/test/genie-app

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3  # Checkout the code from the repository

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}  # Use the private key you added earlier

    - name: Deploy to Remote Server
      run: |
        ssh -v -o StrictHostKeyChecking=no $REMOTE_USER@$REMOTE_HOST "
          mkdir -p $REMOTE_DIR &&
          cd $REMOTE_DIR &&
          if [ -d .git ]; then
            git reset --hard &&
            git pull origin master
          else
            git clone --branch master $REPOSITORY_URL .
          fi &&
          docker compose down &&
          docker compose up -d
        "
